### ISSUE TITLE
helper.py in hack_python is empty

### ISSUE THREAD

**Issue by rowilken** [samsja/hack_python#4]
Hi,

I wanted to have a closer look on the hack you presented in the lightning talk but it seems like you forgot to upload the code for the helper. Anyway: nice talk!

Kind regards,
Roland

**Comment by samsja** [comment]
hey @rowilken the code is in the pull request https://github.com/samsja/hack_python/pull/2 bc I wanted to showcase how we can hack it with a pr. But you are right I should probably merge it 

I am glad that you liked the talk

**Comment by rowilken** [comment]
OK, I overlooked that or maybe you also mentioned this in the talk, not sure. Reminder for myself: no bug reports before the first coffee ;-)
